spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: tickets-service
          uri: 'http://localhost:5051'
          predicates:
            - Path=/tickets/**

server:
  port: 9090