spring:
  application:
    name: tickets-service
  cloud:
    stream:
#      bindings:
#        output-out-0:
#          destination: ticketChangeTopic
#          binder: local_rabbit
      bindings:
        output:
          destination: ticketOrderedInput
          contentType: application/json
          binder: local_rabbit
        input:
          destination: paymentSuccessInput
          contentType: application/json
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest


server:
  port: 5051